### ISSUE TITLE
مشکل در استفاده از تب

### ISSUE THREAD

**Issue by hofa77** [cedarstudios/cedarmaps-react-native-sdk#10]
سلام

وقتی داریم از تب ها استفاده میکنیم 
نقشه در تب اول لود میشه
وقتی تب نقشه رو عوض میکنیم و به یک تب دیگه میریم
و دوباره تب نقشه رو میزنیم
صفحه نقشه کاملا سیاه میشه
و این مشکل فقط وقتی هست که داریم از تب ها استفاده میکنیم

**Comment by ghost** [comment]
سلام. لطفاً مشکلات را با نمونه کد گزارش دهید. شرایط دستگاه خود اعم از ورژن سیستم عامل، ورژن ری‌اکت‌-نیتیو و ... را نیز به طور دقیق شرح دهید. همچنین اینکه مشکل را در چه پلتفورمی مشاهده میکنید ذکر کنید.

**Comment by sdtaheri** [comment]
This issue is closed due to inactivity.
