### ISSUE TITLE
custom image not working on PointAnnotation in Android

### ISSUE THREAD

**Issue by amirito** [cedarstudios/cedarmaps-react-native-sdk#13]
I'm trying to use custom marker 
when I use `Image` in `PointAnnotation`, it doesn't show any image in android 
`<Image source={require('route/to/image.png')} style={{width: 25, height: 25}}/>`

but when I try to draw custom shape, it works fine
` <View style={{width: 20, height: 20, backgroundColor: 'green'}}  />`

**Comment by sdtaheri** [comment]
According to [Mapbox documentation](https://github.com/react-native-mapbox-gl/maps/blob/master/docs/PointAnnotation.md), `PointAnnotation` is about to get deprecated. Please use `ShapeSource` or [`SymbolLayer`](https://github.com/react-native-mapbox-gl/maps/blob/523ad3bc19c04f2645c39398c85d34a916035449/docs/SymbolLayer.md) instead. For showing images, you could use `iconImage` style.

**Comment by amirito** [comment]
@sdtaheri thanks
it works
