### ISSUE TITLE
سلام خسته نباشید توی هر دو پلتفرم این ارور رو داریم مشکل از چیه ؟ من دقیقا مد سمپل شمارو استفاده کردم

### ISSUE THREAD

**Issue by MasoudSadeghy** [cedarstudios/cedarmaps-react-native-sdk#9]
null is not an object (evaluating 'MapboxGL.UserTrackingModes')

**Comment by sinaabadi** [comment]
Hi @MasoudSadeghy
Please post your code (CedarMap Component) here.

**Comment by nimolix** [comment]
I'm closing the issue since there was no additional feedback from reporter.
